#ifndef CONFIG
#define CONFIG

#define CONFIG_TOUCHSCREEN_TIMER_PERIOD 10.0E-3
#define CONFIG_GAME_TIMER_PERIOD 45.0E-3

#define LIGHT_LENGTH 3

// Speed of bikes
#define CONFIG_BIKE_DISTANCE_PER_SECOND 40
#define CONFIG_BIKE_DISTANCE_PER_TICK                                         \
  (CONFIG_BIKE_DISTANCE_PER_SECOND * CONFIG_GAME_TIMER_PERIOD)

#define CONFIG_COLOR_ENEMY DISPLAY_RED
#define CONFIG_COLOR_PLAYER DISPLAY_GREEN

#endif /* CONFIG */
